// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijyqkojwxtcxnvlvafwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqeXFrb2p3eHRjeG52bHZhZndnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4NTU3NzIsImV4cCI6MjA1MzQzMTc3Mn0.nYrAnLCS1q5FLioJuKldQJP4mwybcgtDGHRZVuUyo2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);